# Generated by Django 4.2.3 on 2023-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floating_ip", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floatipcounter",
            name="ipaddress",
            field=models.GenericIPAddressField(default="1.1.1.1"),
            preserve_default=False,
        ),
    ]
