# Generated by Django 4.2.18 on 2025-04-13 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtance', '0002_virtance_type'),
        ('size', '0003_dbms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(blank=True, choices=[('create', 'Database is creating...'), ('delete', 'Database is deleting...'), ('reboot', 'Database is rebooting...'), ('resize', 'Database is resizing...'), ('rename', 'Database is renaming...'), ('restore', 'Database is restoring...'), ('snapshot', 'Database is taking a snapshot...'), ('shutdown', 'Database is shutting down...'), ('power_on', 'PDatabase is powering on...'), ('power_off', 'Database is powering off...'), ('power_cycle', 'Database is power cycling...'), ('password_reset', 'Reseting password...'), ('enable_backups', 'Backups are being enabled...'), ('disable_backups', 'Backups are being disabled...')], default='create', max_length=40, null=True)),
                ('private_key', models.TextField()),
                ('admin_secret', models.TextField()),
                ('master_secret', models.TextField()),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('dbms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='size.dbms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('virtance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='virtance.virtance')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
                'ordering': ['-id'],
            },
        ),
    ]
