# Generated by Django 4.2.3 on 2024-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("size", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="type",
            field=models.CharField(
                choices=[("lbaas", "Load Balancer"), ("virtance", "Virtance")], default="virtance", max_length=50
            ),
        ),
    ]
