# Generated by Django 4.2.18 on 2025-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("size", "0002_size_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBMS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("engine", models.CharField(choices=[("pgsql", "PostgreSQL")], max_length=10)),
                ("version", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=False, verbose_name="Active")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("sizes", models.ManyToManyField(related_name="sizes", to="size.size")),
            ],
            options={
                "verbose_name": "Database Management System",
                "verbose_name_plural": "Database Management Systems",
                "ordering": ["-id"],
            },
        ),
    ]
