# Generated by Django 4.2.18 on 2025-03-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("size", "0002_size_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBMS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("engine", models.CharField(choices=[("pgsql", "PostgreSQL")], max_length=10)),
                ("version", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=False, verbose_name="Active")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "required_size",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="size.size"
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Management System",
                "verbose_name_plural": "Database Management Systems",
                "ordering": ["-id"],
            },
        ),
    ]
