# Generated by Django 4.1.3 on 2022-11-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", models.GenericIPAddressField()),
                ("netmask", models.GenericIPAddressField()),
                ("gateway", models.GenericIPAddressField()),
                ("dns1", models.GenericIPAddressField()),
                ("dns2", models.GenericIPAddressField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("compute", "Compute"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(choices=[(4, "IPv4"), (6, "IPv6")], default=4),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="region.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aggregate",
                "verbose_name_plural": "Aggregates",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
                ("netmask", models.GenericIPAddressField()),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="network.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Address",
                "verbose_name_plural": "IP Addresses",
                "ordering": ["-id"],
            },
        ),
    ]
