# Generated by Django 4.2.3 on 2023-08-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("region", "0001_initial"),
        ("compute", "0001_initial"),
        ("image", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("size", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Virtance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create", "Create"),
                            ("delete", "Delete"),
                            ("reboot", "Reboot"),
                            ("resize", "Resize"),
                            ("rename", "Rename"),
                            ("backup", "Backup"),
                            ("rebuild", "Rebuild"),
                            ("restore", "Restore"),
                            ("snapshot", "Snapshot"),
                            ("shutdown", "Shutdown"),
                            ("power_on", "Power On"),
                            ("power_off", "Power Off"),
                            ("power_cycle", "Power Cycle"),
                            ("password_reset", "Password Reset"),
                            ("enable_backups", "Enable Backups"),
                            ("disable_backups", "Disable Backups"),
                            ("enable_recovery_mode", "Enable Recovery Mode"),
                            ("disable_recovery_mode", "Disable Recovery Mode"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("disk", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("user_data", models.TextField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_recovery_mode", models.BooleanField(default=False)),
                ("is_backup_enabled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "compute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compute.compute",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="region.region"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="size.size"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="image.image"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance",
                "verbose_name_plural": "Virtances",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VirtanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40)),
                ("message", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance History",
                "verbose_name_plural": "Virtance Histories",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VirtanceError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=40, null=True)),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance Error",
                "verbose_name_plural": "Virtance Errors",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VirtanceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
                ),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stopped", models.TextField(blank=True, null=True)),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="size.size"
                    ),
                ),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance Counter",
                "verbose_name_plural": "Virtance Counters",
                "ordering": ["-id"],
            },
        ),
    ]
