# Generated by Django 4.1.3 on 2022-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtance",
            name="user_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
