# Generated by Django 4.2.3 on 2023-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtancecounter",
            name="backup_amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="virtancecounter",
            name="license_amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
