# Generated by Django 4.2.3 on 2024-05-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtance",
            name="type",
            field=models.CharField(
                choices=[
                    ("virtance", "Virtance"),
                    ("k8aas", "Kubernetes"),
                    ("dbaas", "Database"),
                    ("lbaas", "Load Balancer"),
                ],
                default="virtance",
                max_length=40,
            ),
        ),
    ]
