# Generated by Django 4.1.3 on 2022-12-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compute", "0001_initial"),
        ("virtance", "0002_virtance_user_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtance",
            name="compute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="compute.compute",
            ),
        ),
    ]
