# Generated by Django 4.2 on 2023-04-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0002_virtance_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtance",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Create"),
                    ("delete", "Delete"),
                    ("reboot", "Reboot"),
                    ("resize", "Resize"),
                    ("rename", "Rename"),
                    ("rebuild", "Rebuild"),
                    ("restore", "Restore"),
                    ("snapshot", "Snapshot"),
                    ("shutdown", "Shutdown"),
                    ("power_on", "Power On"),
                    ("power_off", "Power Off"),
                    ("password_reset", "Password Reset"),
                    ("enable_backups", "Enable Backups"),
                    ("disable_backups", "Disable Backups"),
                    ("enable_recovery_mode", "Enable Recovery Mode"),
                    ("disable_recovery_mode", "Disable Recovery Mode"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VirtanceError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=40, null=True)),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance Error",
                "verbose_name_plural": "Virtance Errors",
                "ordering": ["-id"],
            },
        ),
    ]
