# Generated by Django 4.2 on 2023-04-22 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0004_virtance_is_recovery_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtance",
            old_name="image",
            new_name="template",
        ),
    ]
