# Generated by Django 4.2 on 2023-05-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("size", "0001_initial"),
        ("virtance", "0005_rename_image_virtance_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtanceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
                ),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stopped", models.TextField(blank=True, null=True)),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="size.size"
                    ),
                ),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtance Counter",
                "verbose_name_plural": "Virtance Counters",
                "ordering": ["-id"],
            },
        ),
    ]
