# Generated by Django 4.2 on 2023-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0007_alter_virtance_event_virtancehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtance",
            name="is_backup_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
