# Generated by Django 4.2 on 2023-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0008_virtance_is_backup_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtance",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Create"),
                    ("delete", "Delete"),
                    ("reboot", "Reboot"),
                    ("resize", "Resize"),
                    ("rename", "Rename"),
                    ("backup", "Backup"),
                    ("rebuild", "Rebuild"),
                    ("restore", "Restore"),
                    ("snapshot", "Snapshot"),
                    ("shutdown", "Shutdown"),
                    ("power_on", "Power On"),
                    ("power_off", "Power Off"),
                    ("power_cycle", "Power Cycle"),
                    ("password_reset", "Password Reset"),
                    ("enable_backups", "Enable Backups"),
                    ("disable_backups", "Disable Backups"),
                    ("enable_recovery_mode", "Enable Recovery Mode"),
                    ("disable_recovery_mode", "Disable Recovery Mode"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
