# Generated by Django 4.2.3 on 2024-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="type",
            field=models.CharField(
                choices=[
                    ("lbaas", "Load Balancer"),
                    ("custom", "Custom"),
                    ("backup", "Backup"),
                    ("snapshot", "Snapshot"),
                    ("application", "Application"),
                    ("distribution", "Distribution"),
                ],
                default="snapshot",
                max_length=50,
            ),
        ),
               migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["type", "-id"], "verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
    ]
