# Generated by Django 4.2 on 2023-04-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("virtance", "0005_rename_image_virtance_template"),
        ("image", "0002_image_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="virtance.virtance",
            ),
        ),
    ]
