# Generated by Django 4.2.3 on 2023-11-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("stopped", models.TextField(blank=True, null=True)),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="image.image")),
            ],
            options={
                "verbose_name": "Snapshot Counter",
                "verbose_name_plural": "Snapshots Counters",
                "ordering": ["-id"],
            },
        ),
    ]
