# Generated by Django 4.2.18 on 2025-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0003_alter_image_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="type",
            field=models.CharField(
                choices=[
                    ("dbaas", "Database"),
                    ("lbaas", "Load Balancer"),
                    ("custom", "Custom"),
                    ("backup", "Backup"),
                    ("snapshot", "Snapshot"),
                    ("application", "Application"),
                    ("distribution", "Distribution"),
                ],
                default="snapshot",
                max_length=50,
            ),
        ),
    ]
