# Generated by Django 4.2.3 on 2023-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0004_imageerror"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Creating"),
                    ("delete", "Deleting"),
                    ("restore", "Restoring"),
                    ("convert", "Converting"),
                    ("transfer", "Transfering"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
