# Generated by Django 4.1.3 on 2022-11-23 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("hostname", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "region",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="region.region"),
                ),
            ],
            options={
                "verbose_name": "Compute",
                "verbose_name_plural": "Computes",
                "ordering": ["-id"],
            },
        ),
    ]
