# Generated by Django 4.1.3 on 2022-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compute",
            name="arch",
            field=models.CharField(
                choices=[("x86_64", "X64"), ("aarch64", "ARM64")],
                default="x86_64",
                max_length=50,
            ),
        ),
    ]
