# Generated by Django 4.2.3 on 2023-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ipv6", "IPv6"),
                            ("resize", "Resize"),
                            ("volume", "Volume"),
                            ("backup", "Backup"),
                            ("snapshot", "Snapshot"),
                            ("one_click", "One-Click"),
                            ("floating_ip", "Floating IP"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False, verbose_name="Active")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Deleted")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("features", models.ManyToManyField(related_name="features", to="region.feature")),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["-id"],
            },
        ),
    ]
