# Generated by Django 4.2.3 on 2023-11-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ["id"], "verbose_name": "Feature", "verbose_name_plural": "Features"},
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                choices=[
                    ("ipv6", "IPv6"),
                    ("resize", "Resize"),
                    ("volume", "Volume"),
                    ("backup", "Backup"),
                    ("snapshot", "Snapshot"),
                    ("one_click", "One-Click"),
                    ("floating_ip", "Floating-IP"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
