# Generated by Django 4.2.18 on 2025-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                choices=[
                    ("ipv6", "IPv6"),
                    ("resize", "Resize"),
                    ("volume", "Volume"),
                    ("backup", "Backup"),
                    ("snapshot", "Snapshot"),
                    ("one_click", "1Click"),
                    ("floating_ip", "Float-IP"),
                    ("load_balancer", "LBaaS"),
                    ("database", "DBaaS"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
