webvirtcloud_crispy_class_converters = {
    "textinput": "form-control 1111",
    "passwordinput": "form-control",
    "emailinput": "form-control",
    "urlinput": "form-control",
    "numberinput": "form-control",
    "dateinput": "form-control",
    "textarea": "form-control",
    "radioset": "form-check",
    "checkboxinput": "form-check-input",
    "checkboxselectmultiple": "form-check",
    "radioselect": "form-check",
    "fileinput": "form-control",
    "select": "form-select",
    "selectmultiple": "form-select",
    "password": "form-control",
    "hidden": "form-control",
}
