# Generated by Django 4.2.3 on 2023-09-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firewall.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("virtance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firewall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create", "Creating"),
                            ("update", "Updating"),
                            ("delete", "Deleting"),
                            ("attach", "Attaching"),
                            ("detach", "Detaching"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField()),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Firewall",
                "verbose_name_plural": "Firewalls",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "direction",
                    models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=10),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True, choices=[("tcp", "TCP"), ("udp", "UDP"), ("icmp", "ICMP")], max_length=10, null=True
                    ),
                ),
                (
                    "action",
                    models.CharField(choices=[("DROP", "DROP"), ("ACCEPT", "ACCEPT")], default="DROP", max_length=50),
                ),
                ("ports", models.CharField(default=0, max_length=12, validators=[firewall.models.validate_ports])),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_system", models.BooleanField(default=False)),
                ("firewall", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="firewall.firewall")),
            ],
            options={
                "verbose_name": "Firewall Rule",
                "verbose_name_plural": "Firewall Rules",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FirewallVirtance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("firewall", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="firewall.firewall")),
                ("virtance", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtance.virtance")),
            ],
            options={
                "verbose_name": "Firewall Virtance",
                "verbose_name_plural": "Firewall Virtances",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Cidr",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.GenericIPAddressField(default="0.0.0.0")),
                ("prefix", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="firewall.rule")),
            ],
            options={
                "verbose_name": "CIDR",
                "verbose_name_plural": "CIDRs",
                "ordering": ["-id"],
            },
        ),
    ]
