# Generated by Django 4.2.3 on 2023-10-27 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("virtance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firewall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallvirtance",
            name="virtance",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="virtance.virtance"),
        ),
        migrations.AddField(
            model_name="firewall",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="cidr",
            name="rule",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="firewall.rule"),
        ),
    ]
