# Generated by Django 4.1.3 on 2022-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("virtance", "0003_alter_virtance_compute"),
        ("keypair", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyPairVirtance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "keypair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="keypair.keypair",
                    ),
                ),
                (
                    "virtance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="virtance.virtance",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSH Key Virtance",
                "verbose_name_plural": "SSH Keys Virtance",
                "ordering": ["-id"],
            },
        ),
    ]
